apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-autoscale 
  namespace: digitalroute
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-deployment
  minReplicas: 6
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50