# {% for deployment in deployments_list %}
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ deployment.name }}
#   labels:
#     app: {{ deployment.label }}
# spec:
#   replicas: {{ deployment.replicas }}
#   selector:
#     matchLabels:
#       app: {{ deployment.label }}
#   template:
#     metadata:
#       labels:
#         app: {{ deployment.label }}
#     spec:
#       containers:
#       - name: {{ deployment.container_name }}
#         image: {{ deployment.image }}
#         ports:
#         - containerPort: {{ deployment.container_port }}

# {% endfor %}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
  namespace: digitalroute
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: workload
                  operator: In
                  values:
                  - production
      containers:
      - name: hello
        image: navoda/digitalroute-helloworld
        ports:
        - name: liveness-port
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: site-data
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - all
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 2
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: liveness-port
        startupProbe:
          httpGet:
            path: /actuator/health
            port: liveness-port
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: pvclaim-1
