---
# - name: deploy k8s add-ons
#   hosts: localhost
#   connection: local
#   gather_facts: no

#   vars:
#     ansible_python_interpreter: "{{ ansible_playbook_python }}"
#     k8s_kubeconfig: ~/.kube/config
#     k8s_manifests_base_dir: templates/
#     k8s_manifests_state: present
#     k8s_force: false
#     k8s_no_log: false
    
  tasks:
  - import_tasks: tasks/namespaces.yaml
   tags: namespaces
  - import_tasks: tasks/volumes.yaml
    tags: volumes
  - import_tasks: tasks/deployments.yaml
    tags: deployments
  - import_tasks: tasks/services.yaml
    tags: services
  - import_tasks: tasks/auto-scaler.yaml
    tags: auto-scaler
  - import_tasks: tasks/pdm.yaml
    tags: pdm
  - import_tasks: tasks/secrets.yaml
    tags: secrets
  - import_tasks: tasks/ingress.yaml
    tags: ingress    